# Generated by Django 5.1.6 on 2025-03-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
    ]
